# Generated by Django 4.2 on 2023-05-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='userc',
        ),
    ]
