# Generated by Django 4.2 on 2023-05-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_rename_user_customer_userc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('people', models.IntegerField()),
                ('amount', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('eventpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.events')),
                ('menupack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.customer')),
            ],
        ),
    ]
